### PR TITLE
Fixed double compression of one message

### LINKED ISSUE #501: Double sending of topic message creates double comporessed data

### PR DESCRIPTION
**Pull request by alex268**
Fixes #501

### CODE REVIEW

File: topic/src/main/java/tech/ydb/topic/write/impl/EnqueuedMessage.java [hunk 1]
```diff
@@ -1,78 +1,114 @@
...
 
-    public long getCompressedSizeBytes() {
-        return compressedSizeBytes;
+    public IOException getCompressError() {
+        return comporessError;
     }
 
-    public void setCompressedSizeBytes(long compressedSizeBytes) {
-        this.compressedSizeBytes = compressedSizeBytes;
+    public void encode(String id, Codec codec) {
```
Comment (pnv1) [inline topic/src/main/java/tech/ydb/topic/write/impl/EnqueuedMessage.java:67]: id -> writerId

File: topic/src/main/java/tech/ydb/topic/write/impl/EnqueuedMessage.java [hunk 2]
```diff
@@ -52,27 +52,27 @@ public boolean isReady() {
         return isReady;
     }
 
-    public long getOriginLength() {
+    public long gitOriginSize() {
```
Comment (pnv1) [inline topic/src/main/java/tech/ydb/topic/write/impl/EnqueuedMessage.java:55]: git -> get

I'd prefer something from these:

- getOriginalSize()
This is a clear and widely used naming convention that communicates the method returns the size of the message before any compression or transformation.
✅ Suitable when referring to the size as it was when the message was initially created.

- getUncompressedSize()
This name emphasizes that the method returns the size of the message in its uncompressed state.
✅ Ideal if compression is the main factor affecting the message size.

- getInitialSize()
"Initial" implies the size at the very beginning, before any modifications (such as compression or transformations).
✅ Good for highlighting the "first known" size value.

File: topic/src/main/java/tech/ydb/topic/write/impl/EnqueuedMessage.java [hunk 3]
```diff
@@ -1,78 +1,114 @@
...
+        this.items = message.getMetadataItems();
+        this.seqNo = message.getSeqNo();
 
-    public CompletableFuture<WriteAck> getFuture() {
-        return future;
-    }
-
-    public boolean isCompressed() {
-        return isCompressed.get();
+        this.originLength = bytes.length;
```
Comment (pnv1) [inline topic/src/main/java/tech/ydb/topic/write/impl/EnqueuedMessage.java:46]: originalSize?

**Review by pnv1 — APPROVED** [review]
